# Generated by Django 6.0.7 on 2026-07-30 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManage', '0003_remove_student_user_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='users',
        ),
    ]
