# Generated by Django 6.0.7 on 2026-07-30 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManage', '0004_rename_user_user_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='users',
            new_name='user',
        ),
    ]
